// PROJECT DATA - Organized by Category

const projectsData = {
    'ai-ml': {
        title: 'AI & MACHINE LEARNING',
        projects: [
            {
                title: 'NUSAF IV',
                description: 'AI-POWERED SOCIAL WELFARE PLATFORM FOR UGANDA GOVERNMENT. FACIAL RECOGNITION FOR BENEFICIARY VERIFICATION. FRAUD DETECTION ML THAT FLAGS SUSPICIOUS REGISTRATIONS. CNN-BASED FINGERPRINT CLASSIFICATION. DYNAMIC SENTIMENT ANALYSIS ENGINE. OFFLINE-FIRST MOBILE ARCHITECTURE FOR RURAL DEPLOYMENT WITH AUTO-SYNC WHEN CONNECTIVITY RESTORED.',
                tech: ['TENSORFLOW', 'PYTORCH', 'OPENCV', 'DJANGO', 'ANDROID', 'AWS', 'FACIAL RECOGNITION', 'FRAUD ML'],
                link: null,
                status: 'DEPLOYED'
            },
            {
                title: 'MIFUGO LIVESTOCK TRACKING',
                description: 'REVOLUTIONARY CNN-BASED CATTLE IDENTIFICATION SYSTEM FOR KENYA GOVERNMENT. IDENTIFIES CATTLE THROUGH MUZZLE PATTERN RECOGNITION, CREATING BIOMETRIC ID FOR LIVESTOCK. MOBILE-OPTIMIZED INFERENCE. MANAGES 50,000+ CATTLE RECORDS. ANTI-THEFT TRACKING SYSTEM DEPLOYED VIA SMARTPHONES ONLY.',
                tech: ['PYTORCH', 'CNN', 'MOBILE AI', 'ANDROID', 'IMAGE PROCESSING', 'COMPUTER VISION'],
                link: null,
                status: 'PRODUCTION'
            },
            {
                title: 'FRAUD DETECTION ENGINE',
                description: 'INTELLIGENT FRAUD MANAGEMENT SYSTEM FOR BANKING AND FINTECH PLATFORMS. PATTERN RECOGNITION AND ANOMALY DETECTION. REAL-TIME RISK SCORING. LEARNS FROM USER INTERACTIONS DYNAMICALLY. INTEGRATED WITH MULTIPLE FINANCIAL INSTITUTIONS ACROSS EAST AFRICA.',
                tech: ['SCIKIT-LEARN', 'PYTHON', 'TENSORFLOW', 'REAL-TIME ML', 'RISK ANALYTICS'],
                link: null,
                status: 'DEPLOYED'
            },
            {
                title: 'SENTIMENT ANALYSIS PLATFORM',
                description: 'DYNAMIC SENTIMENT ANALYSIS ENGINE THAT LEARNS FROM USER INTERACTIONS. ASSISTS WITH BENEFICIARY SCREENING AND FLAGGING. INTEGRATED TO RISK ENGINE FOR MONETARY FRAUD DETECTION. NLP-BASED TEXT CLASSIFICATION WITH CONTINUOUS LEARNING CAPABILITIES.',
                tech: ['NLP', 'TENSORFLOW', 'PYTHON', 'BERT', 'TEXT CLASSIFICATION'],
                link: null,
                status: 'ACTIVE'
            }
        ]
    },
    'vision-ocr': {
        title: 'COMPUTER VISION & OCR',
        projects: [
            {
                title: 'SAFARICOM OCR SYSTEM',
                description: 'ENTERPRISE-GRADE OCR AUTOMATION FOR SAFARICOM. CONVERTS SCANNED DOCUMENTS TO STRUCTURED DATA. MULTI-LANGUAGE SUPPORT (ENGLISH, SWAHILI). DOCUMENT CLASSIFICATION AND ROUTING. EDMS INTEGRATION PIPELINE. PROCESSES 10K+ DOCUMENTS DAILY.',
                tech: ['TESSERACT', 'OPENCV', 'PYTHON', 'FLASK', 'DOCUMENT AI', 'NLP'],
                link: null,
                status: 'PRODUCTION'
            },
            {
                title: 'CIC INSURANCE CLAIMS PROCESSOR',
                description: 'MEDICAL CLAIMS OCR SYSTEM FOR CIC INSURANCE. IMAGE-TO-TEXT CONVERSION FOR MEDICAL DOCUMENTS. INTELLIGENT DOCUMENT CLASSIFICATION. ELIMINATES MANUAL DATA ENTRY ERRORS. SAVES MILLIONS IN UNDERWRITING COSTS. 90% REDUCTION IN PROCESSING TIME.',
                tech: ['TESSERACT', 'OPENCV', 'PYTHON', 'MACHINE LEARNING', 'DOCKER'],
                link: null,
                status: 'DEPLOYED'
            },
            {
                title: 'MEDICAL CLAIMS AUTOMATION',
                description: 'END-TO-END AUTOMATION PIPELINE FOR MEDICAL INSURANCE CLAIMS. EXTRACTS DATA FROM PRESCRIPTIONS, INVOICES, AND MEDICAL REPORTS. VALIDATES AGAINST POLICY COVERAGE. AUTO-GENERATES APPROVAL/REJECTION DECISIONS. FULL API INTEGRATION WITH EXISTING SYSTEMS.',
                tech: ['COMPUTER VISION', 'OCR', 'PYTHON', 'REST APIs', 'MICROSERVICES'],
                link: null,
                status: 'LIVE'
            },
            {
                title: 'DOCUMENT INTELLIGENCE PLATFORM',
                description: 'MULTI-PURPOSE OCR AND DOCUMENT PROCESSING PLATFORM. HANDLES INVOICES, RECEIPTS, CONTRACTS, ID DOCUMENTS. INTELLIGENT FIELD EXTRACTION. WORKFLOW AUTOMATION. ENTERPRISE SECURITY AND COMPLIANCE. SCALABLE CLOUD ARCHITECTURE.',
                tech: ['OPENCV', 'TESSERACT', 'AWS', 'DOCKER', 'KUBERNETES', 'MICROSERVICES'],
                link: null,
                status: 'ENTERPRISE'
            }
        ]
    },
    'blockchain': {
        title: 'BLOCKCHAIN & WEB3',
        projects: [
            {
                title: 'BIOMETRIC IDENTITY PLATFORM',
                description: 'EMERGING BLOCKCHAIN PLATFORM COMBINING BIOMETRIC MARKERS INTO SMART CONTRACTS. FINGERPRINTS AND MUZZLE DATA (LIVESTOCK) STORED ON DECENTRALIZED LEDGER. CREATES IMMUTABLE IDENTITY RECORDS. ENABLES TRUSTLESS VERIFICATION WITHOUT CENTRAL AUTHORITY.',
                tech: ['BLOCKCHAIN', 'SMART CONTRACTS', 'SOLIDITY', 'WEB3', 'BIOMETRICS', 'CRYPTOGRAPHY'],
                link: null,
                status: 'IN DEVELOPMENT'
            },
            {
                title: 'LIVESTOCK INVESTMENT PLATFORM',
                description: 'DECENTRALIZED ASSET LEDGER FOR LIVESTOCK TRADING AND INVESTMENT. SMART CONTRACTS FOR FRACTIONAL OWNERSHIP. TOKENIZED CATTLE ASSETS. ENABLES MICRO-LOANS BACKED BY LIVESTOCK. TRACEABLE OWNERSHIP HISTORY. INTEGRATES WITH MIFUGO BIOMETRIC SYSTEM.',
                tech: ['ETHEREUM', 'SMART CONTRACTS', 'SOLIDITY', 'WEB3.JS', 'IPFS'],
                link: null,
                status: 'BETA'
            },
            {
                title: 'MICRO-LOAN INFRASTRUCTURE',
                description: 'BLOCKCHAIN-BASED MICRO-LENDING PLATFORM FOR RURAL FARMERS. COLLATERAL VERIFICATION VIA BIOMETRIC LIVESTOCK ID. AUTOMATED LOAN DISBURSEMENT AND REPAYMENT. TRANSPARENT INTEREST CALCULATION. CONNECTS LENDERS WITH BORROWERS TRUSTLESSLY.',
                tech: ['BLOCKCHAIN', 'SMART CONTRACTS', 'DeFi', 'WEB3', 'SOLIDITY'],
                link: null,
                status: 'PILOT'
            },
            {
                title: 'DECENTRALIZED IDENTITY LEDGER',
                description: 'SELF-SOVEREIGN IDENTITY SYSTEM FOR UNDERBANKED POPULATIONS. STORES CREDENTIALS, CERTIFICATES, AND FINANCIAL HISTORY ON BLOCKCHAIN. USER-CONTROLLED DATA SHARING. ENABLES FINANCIAL INCLUSION. PRIVACY-PRESERVING VERIFICATION.',
                tech: ['BLOCKCHAIN', 'DIDs', 'VERIFIABLE CREDENTIALS', 'ZERO-KNOWLEDGE PROOFS'],
                link: null,
                status: 'RESEARCH'
            }
        ]
    },
    'banking': {
        title: 'INTERNET BANKING',
        projects: [
            {
                title: 'VCB BANK IB',
                description: 'PRODUCTION-GRADE MOBILE BANKING APPLICATION FOR VCB BANK. ANDROID AND iOS NATIVE APPS. FINACLE CORE BANKING INTEGRATION. SECURE AUTHENTICATION WITH BIOMETRICS. REAL-TIME BALANCE UPDATES. FUND TRANSFERS, BILL PAYMENTS, ACCOUNT MANAGEMENT. CBK COMPLIANCE.',
                tech: ['ANDROID', 'IOS', 'KOTLIN', 'SWIFT', 'FINACLE', 'Java', 'SECURITY'],
                link: null,
                status: 'LIVE'
            },
            {
                title: 'CARITAS BANK MOBILE',
                description: 'INTERNET BANKING MOBILE PLATFORM FOR CARITAS BANK. FULL-FEATURED BANKING APP WITH MODERN UI/UX. ACCOUNT STATEMENTS, TRANSACTION HISTORY, LOAN APPLICATIONS. PUSH NOTIFICATIONS FOR TRANSACTIONS. QR CODE PAYMENTS. PRODUCTION DEPLOYMENT COMPLETE.',
                tech: ['ANDROID', 'IOS', 'REACT NATIVE', 'FINACLE', 'REST APIs', 'SECURITY'],
                link: null,
                status: 'PRODUCTION'
            },
            {
                title: 'STANDARD CHARTERED SOLV',
                description: 'REVERSE FACTORING AND DEALER FINANCING PLATFORM. MOBILE AND WEB APPLICATION. ENABLES SUPPLY CHAIN FINANCING. INVOICE MANAGEMENT AND EARLY PAYMENT OPTIONS. CONNECTS SUPPLIERS WITH BUYERS. AUTOMATED APPROVAL WORKFLOWS.',
                tech: ['REACT', 'NODE.JS', 'ANDROID', 'iOS', 'MICROSERVICES', 'FINTECH'],
                link: null,
                status: 'DEPLOYED'
            },
            {
                title: 'EQUITY BANK RECONCILIATION',
                description: 'AUTOMATED FINACLE REPORTS AND RECONCILIATION ENGINE FOR EQUITY BANK. REAL-TIME TRANSACTION MATCHING. DISCREPANCY DETECTION AND ALERTS. AUTOMATED REPORT GENERATION. CBK REGULATORY COMPLIANCE. HANDLES MILLIONS OF TRANSACTIONS DAILY.',
                tech: ['DJANGO', 'AIRFLOW', 'CELERY', 'FINACLE APIs', 'POSTGRESQL', 'BANKING'],
                link: null,
                status: 'ENTERPRISE'
            }
        ]
    },
    'enterprise': {
        title: 'ENTERPRISE SYSTEMS',
        projects: [
            {
                title: 'MARURUI CONCRETE ERP',
                description: 'COMPREHENSIVE ERP SYSTEM FOR CONCRETE MANUFACTURING. IOT-CONNECTED WEIGHBRIDGE INTEGRATION. AUTOMATED BATCHING TRACKING. VEHICLE WEIGHT MANAGEMENT (ENTRY/EXIT). AUTO-GENERATES INVOICES AND RECEIPTS. REAL-TIME INVENTORY SYNC. DISPATCH AND BILLING WORKFLOWS.',
                tech: ['.NET', 'C#', 'IoT', 'WEIGHBRIDGE', 'ERP', 'MYSQL', 'REAL-TIME SYSTEMS'],
                link: null,
                status: 'DEPLOYED'
            },
            {
                title: 'VCB-CBK REPORTING SYSTEM',
                description: 'AUTOMATED REGULATORY REPORTING PLATFORM FOR CENTRAL BANK OF KENYA. CONNECTS FINACLE CORE BANKING WITH CBK SYSTEMS. SCHEDULED REPORT GENERATION. DATA VALIDATION AND COMPLIANCE CHECKS. AUDIT TRAIL. DELIVERED ON STRICT DEADLINE WITH ZERO ERRORS.',
                tech: ['DJANGO', 'AIRFLOW', 'CELERY', 'RABBITMQ', 'FINACLE', 'COMPLIANCE'],
                link: null,
                status: 'PRODUCTION'
            },
            {
                title: 'MULTI-TENANT POS SYSTEMS',
                description: 'MODULAR POINT-OF-SALE PLATFORM FOR RETAIL AND HOSPITALITY. OFFLINE SYNC CAPABILITY. BARCODE SCANNING AND INVENTORY TRACKING. USER-LEVEL PERMISSIONS. AUTOMATED DAILY RECONCILIATIONS. M-PESA INTEGRATION. RECEIPT PRINTING. CLOUD DASHBOARDS.',
                tech: ['SPRING BOOT', 'JAVA', 'MYSQL', 'M-PESA APIs', 'OFFLINE-FIRST', 'MICROSERVICES'],
                link: null,
                status: 'MULTI-CLIENT'
            },
            {
                title: 'NCBA PROPERTY MANAGEMENT',
                description: 'PROPERTY MANAGEMENT PLATFORM FOR NCBA BANK. WEB AND MOBILE APPLICATIONS. TENANT MANAGEMENT, LEASE TRACKING, RENT COLLECTION. MAINTENANCE REQUEST WORKFLOWS. FINANCIAL REPORTING. DOCUMENT MANAGEMENT. INTEGRATED PAYMENT GATEWAYS.',
                tech: ['REACT', 'DJANGO', 'POSTGRESQL', 'ANDROID', 'iOS', 'REST APIs'],
                link: null,
                status: 'LIVE'
            }
        ]
    },
    'uiux': {
        title: 'UI/UX DESIGN',
        projects: [
            {
                title: 'BANKING APPS UI/UX',
                description: 'DESIGNED USER INTERFACES FOR MULTIPLE MOBILE BANKING APPLICATIONS. FOCUS ON ACCESSIBILITY, SIMPLICITY, AND SECURITY. CONDUCTED USER RESEARCH AND USABILITY TESTING. CREATED DESIGN SYSTEMS AND COMPONENT LIBRARIES. FINTECH-SPECIFIC UX PATTERNS.',
                tech: ['FIGMA', 'UI DESIGN', 'UX RESEARCH', 'PROTOTYPING', 'DESIGN SYSTEMS'],
                link: null,
                status: 'ONGOING'
            },
            {
                title: 'DASHBOARD INTERFACES',
                description: 'ENTERPRISE DASHBOARD DESIGN FOR ANALYTICS AND MONITORING PLATFORMS. DATA VISUALIZATION BEST PRACTICES. REAL-TIME METRICS DISPLAY. RESPONSIVE LAYOUTS. DARK MODE SUPPORT. DESIGNED FOR C-LEVEL EXECUTIVES AND OPERATIONS TEAMS.',
                tech: ['FIGMA', 'DATA VIZ', 'DASHBOARDS', 'RESPONSIVE DESIGN', 'ACCESSIBILITY'],
                link: null,
                status: 'PORTFOLIO'
            },
            {
                title: 'PORTFOLIO WEBSITES',
                description: 'PERSONAL AND CORPORATE PORTFOLIO WEBSITES WITH UNIQUE AESTHETICS. BRUTALIST DESIGN, MINIMALISM, 3D EFFECTS. RESPONSIVE AND PERFORMANT. CREATIVE USE OF TYPOGRAPHY AND WHITESPACE. MEMORABLE BRAND EXPERIENCES.',
                tech: ['HTML/CSS', 'THREE.JS', 'JAVASCRIPT', 'RESPONSIVE', 'CREATIVE CODING'],
                link: 'https://github.com/jacke-code',
                status: 'LIVE'
            },
            {
                title: 'MOBILE APP DESIGN',
                description: 'iOS AND ANDROID APP DESIGN FOLLOWING PLATFORM GUIDELINES. HUMAN INTERFACE GUIDELINES (iOS) AND MATERIAL DESIGN (ANDROID). INTERACTIVE PROTOTYPES. ANIMATION SPECIFICATIONS. DESIGN HANDOFF TO DEVELOPERS.',
                tech: ['FIGMA', 'iOS DESIGN', 'MATERIAL DESIGN', 'PROTOTYPING', 'ANIMATIONS'],
                link: null,
                status: 'FREELANCE'
            }
        ]
    }
};
